stages:
  - build
  - deploy

variables:
  BRANCH_NAME: "${CI_COMMIT_TAG%%-*}"
  BRANCH_VERSION: "${CI_COMMIT_TAG#*-}"
  IMAGE_NAME: "$DOCKER_REGISTRY/opala-lab/timeline-api"

docker_image_timeline_api:
  image: docker:20.10.23
  stage: build
  services:
    - docker:20.10-dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$DOCKER_REGISTRY"
    - docker build -t "$IMAGE_NAME:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA" -t "$IMAGE_NAME:$CI_COMMIT_BRANCH-latest" .
    - docker push "$IMAGE_NAME:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA"
    - docker push "$IMAGE_NAME:$CI_COMMIT_BRANCH-latest"

timeline_api_producao_deploy:
  image: alpine:3.17.2
  stage: deploy
  needs:
    - job: docker_image_timeline_api
      artifacts: true
  script:
    - apk update && apk add --update sshpass openssh
    - pwd
    - ls -lah
    - sshpass -p "$FTP_PASS_PRODUCAO" ssh -o StrictHostKeyChecking=no "$FTP_USER@$FTP_HOST_PRODUCAO" -p "$FTP_PORT" 'cd /opt/opalalab/timeline-api/; docker compose down; docker compose pull; docker compose build; docker compose up -d'
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_BRANCH_PRODUCAO
      when: always
