services:
  app:
    build: .
    container_name: api_timeline
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/cache

volumes:
  cache:
